NAME = libft.a

CC = cc
CFLAGS = -Wall -Wextra -Werror

SRCS =	ft_atoi.c				\
				ft_itoa.c				\
				ft_xtoa.c				\
				ft_split.c			\
				ft_nbrlen.c			\
				ft_bzero.c			\
				ft_calloc.c			\
				ft_memchr.c			\
				ft_memcmp.c			\
				ft_memcpy.c			\
				ft_memset.c			\
				ft_strchr.c			\
				ft_strdup.c			\
				ft_strlen.c			\
				ft_substr.c			\
				ft_isalnum.c		\
				ft_isalpha.c		\
				ft_isascii.c		\
				ft_isdigit.c		\
				ft_isprint.c		\
				ft_memmove.c		\
				ft_strjoin.c		\
				ft_strlcat.c		\
				ft_strlcpy.c		\
				ft_tolower.c		\
				ft_strmapi.c		\
				ft_strncmp.c		\
				ft_strnstr.c		\
				ft_strrchr.c		\
				ft_strtrim.c		\
				ft_toupper.c		\
				ft_striteri.c		\
				ft_putstr_fd.c	\
				ft_putnbr_fd.c	\
				ft_putendl_fd.c	\
				ft_putchar_fd.c	\
				ft_struppcase.c

BONUS_SRCS =	ft_lstmap_bonus.c				\
							ft_lstnew_bonus.c				\
							ft_lstlast_bonus.c			\
							ft_lstiter_bonus.c			\
							ft_lstsize_bonus.c			\
							ft_lstclear_bonus.c			\
							ft_lstdelone_bonus.c		\
							ft_lstadd_back_bonus.c	\
							ft_lstadd_front_bonus.c	\

SRCS_OBJS = $(SRCS:.c=.o)
BONUS_OBJS = $(BONUS_SRCS:.c=.o)

all: $(NAME)

$(NAME): $(SRCS_OBJS)
	ar rcs $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@

bonus: $(SRCS_OBJS) $(BONUS_OBJS)
	ar rcs $(NAME) $^

fclean: clean
	rm -rf $(NAME)

clean:
	rm -rf $(SRCS_OBJS) $(BONUS_OBJS)

re: fclean all

.PHONY: all clean fclean re